module.exports = [
  {food: 'bakso', calorie: 283},
  {food: 'dessert', calorie: 49},
  {food: 'egg', calorie: 74},
  {food: 'french_fries', calorie: 211},
  {food: 'fried_rice', calorie: 267},
  {food: 'hamburger', calorie: 257},
  {food: 'meat', calorie: 288},
  {food: 'pizza', calorie: 276},
  {food: 'sate', calorie: 729},
  {food: 'soto', calorie: 101},
  {food: 'soup', calorie: 73},
  {food: 'spaghetti', calorie: 642},
  {food: 'sushi', calorie: 31},
  {food: 'vegfruit', calorie: 261},
];
